baseURL = "http://aiirobyte.github.io/"
title = "Aiirobyte's Blog"
theme = "hugo-theme-tokiwa"
enableEmoji = true
mainSections = ["blog"]

[params]
title = "Aiirobyte's Blog"
author = "Aiirobyte"
description = "Blog by Aiirobyte"