baseURL = "https://aiirobyte.github.io/"
title = "Aiirobyte's Blog"
theme = "hugo-paper"
enableRobotsTXT = true      # generate robots.txt
enableEmoji = true           # use emoji support
hasCJKLanguage = true        # detect CJK languages for word count etc.
preserveTaxonomyNames = true # do not make tag names lowercase
page_view_conter = true

[params]
postDateFormat = "2006-1-2" # override custom date format posts.
mainSections = ['blog', 'review']

color = "linen"
github = "aiirobyte"
twitter = "aiirobyte"

[pages]


[menu]
  [[menu.main]]
    name = "Blog"
    weight = 1
    identifier = "blog"
    url = "/blog/"
  [[menu.main]]
    name = "Review"
    weight = 1
    identifier = "review"
    url = "/review/"
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2